apiVersion: 1

datasources:
  - name: Supabase
    type: postgres
    access: proxy
    url: ${SUPABASE_URL}
    database: postgres
    user: postgres
    secureJsonData:
      password: ${SUPABASE_SERVICE_KEY}
    isDefault: true
    jsonData:
      sslmode: require
      postgresVersion: 1300
    editable: true 