apiVersion: 1

datasources:
  - name: Supabase
    type: postgres
    access: proxy
    url: ${SUPABASE_HOST}:${SUPABASE_PORT}
    database: ${SUPABASE_DB}
    user: ${SUPABASE_USER}
    secureJsonData:
      password: ${SUPABASE_PASSWORD}
    isDefault: true
    jsonData:
      sslmode: require
      postgresVersion: 1300
    editable: true 