apiVersion: 1

datasources:
  - name: Supabase
    type: postgres
    uid: supabase
    access: proxy
    url: ${SUPABASE_HOST}
    database: ${SUPABASE_DB}
    user: ${SUPABASE_USER}
    secureJsonData:
      password: ${SUPABASE_PASSWORD}
    isDefault: true
    jsonData:
      sslmode: ${SUPABASE_SSL_MODE:-disable}
      postgresVersion: 1300
      port: ${SUPABASE_PORT}
    editable: true 